MODEL:
  META_ARCHITECTURE: "SOLOv2"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("trashcan_instance_train",)
  TEST: ("trashcan_instance_val",)
SOLVER:
  IMS_PER_BATCH: 6
  BASE_LR: 0.001
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 400
  STEPS: (3000, 4000)
  MAX_ITER: 4500
  CHECKPOINT_PERIOD: 200
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 600
  MASK_FORMAT: "bitmask"
VERSION: 2


